server:
  port: 8084

spring:
  application:
    name: APIGATEWAY

  cloud:
    gateway:
      routes:

        # USER SERVICE ROUTE
        - id: USERSERVICE
          uri: lb://USERSERVICE
          predicates:
            - Path=/api/users/**

        # RATING SERVICE ROUTE
        - id: RATINGSERVICE
          uri: lb://RATINGSERVICE
          predicates:
            - Path=/api/ratings/**

        # HOTEL SERVICE ROUTE
        - id: HOTELSERVICE
          uri: lb://HOTELSERVICE
          predicates:
            - Path=/api/hotels/**, /api/staffs/**
  config:
    import: configserver:http://localhost:8085

#eureka:
#  instance:
#    prefer-ip-address: true
#
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: gateway
